const sampleRecipes = [
    {
        title: "Butter Chicken",
        type: "Lunch",
        meal: "Non-veg",
        image: "https://foodess.com/wp-content/uploads/2022/10/Foodess-Best-Butter-Chicken-1-2.jpg",
        keyIngredient: "Chicken",
        subIngredient_1: "Tomato",
        subIngredient_2: "Cream",
        otherIngredients: "500g chicken, 1 cup tomato puree, 1/2 cup fresh cream, 2 tbsp butter, 1 tbsp ginger-garlic paste, 1 tsp garam masala, 1 tsp red chili powder, 1 tsp turmeric, 1 tsp cumin powder, salt to taste, fresh coriander",
        process: "Marinate chicken with spices for 30 mins. Grill or pan-fry. In a pan, melt butter, add ginger-garlic paste, tomato puree and spices. Cook until oil separates. Add chicken and simmer. Finish with fresh cream and garnish with coriander.",
        time: "50 mins",
        calorie: 450
    },
    {
        title: "Palak Paneer",
        type: "Lunch",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/06/palak-paneer-recipe-500x375.jpg",
        keyIngredient: "Paneer",
        subIngredient_1: "Spinach",
        subIngredient_2: "Cream",
        otherIngredients: "200g paneer, 2 bunches spinach, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp cumin, 1 tsp garam masala, 1/2 cup cream, 2 tbsp oil, salt to taste",
        process: "Blanch spinach and blend to paste. Sauté onions, add ginger-garlic paste, tomatoes and spices. Add spinach puree and cook. Add paneer cubes and simmer. Finish with cream.",
        time: "40 mins",
        calorie: 350
    },
    {
        title: "Chana Masala",
        type: "Lunch",
        meal: "Veg",
        image: "https://minimalistbaker.com/wp-content/uploads/2016/02/AMAZING-Chana-Masala-made-in-1-Pot-So-healthy-flavorful-and-delicious-vegan-glutenfree-chanamasala-recipe-minimalistbaker.jpg",
        keyIngredient: "Chickpeas",
        subIngredient_1: "Tomato",
        subIngredient_2: "Onion",
        otherIngredients: "2 cups cooked chickpeas, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp turmeric, 1 tsp coriander powder, 1 tsp cumin powder, 1 tsp garam masala, 2 tbsp oil, fresh coriander",
        process: "Sauté onions until golden. Add ginger-garlic paste, tomatoes and spices. Cook until oil separates. Add chickpeas with some water. Simmer for 15 mins. Garnish with coriander.",
        time: "35 mins",
        calorie: 320
    },
    {
        title: "Biryani",
        type: "Lunch",
        meal: "Non-veg",
        image: "https://c.ndtvimg.com/2020-12/uimt7tg8_biryani_625x300_30_December_20.jpg",
        keyIngredient: "Rice",
        subIngredient_1: "Chicken",
        subIngredient_2: "Yogurt",
        otherIngredients: "2 cups basmati rice, 500g chicken, 1 cup yogurt, 2 onions, 2 tomatoes, 1 tbsp ginger-garlic paste, whole spices (bay leaf, cardamom, cinnamon), 1 tsp turmeric, 1 tsp red chili powder, saffron strands, fresh mint and coriander",
        process: "Marinate chicken with yogurt and spices. Parboil rice. Layer rice and chicken in a pot with fried onions, herbs and saffron milk. Cook on dum (sealed) for 20-25 mins.",
        time: "60 mins",
        calorie: 550
    },
    {
        title: "Dal Tadka",
        type: "Lunch",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/04/dal-tadka-recipe.jpg",
        keyIngredient: "Lentils",
        subIngredient_1: "Tomato",
        subIngredient_2: "Onion",
        otherIngredients: "1 cup yellow lentils, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp turmeric, 1 tsp cumin seeds, 1 tsp mustard seeds, 2 dried red chilies, 2 tbsp ghee, fresh coriander",
        process: "Cook lentils until soft. In another pan, temper cumin, mustard seeds and chilies in ghee. Add onions, ginger-garlic paste, tomatoes and spices. Mix with cooked dal. Garnish with coriander.",
        time: "30 mins",
        calorie: 280
    },
    {
        title: "Aloo Gobi",
        type: "Lunch",
        meal: "Veg",
        image: "https://i.ytimg.com/vi/YiPHmxX8xpA/maxresdefault.jpg",
        keyIngredient: "Potato",
        subIngredient_1: "Cauliflower",
        subIngredient_2: "Peas",
        otherIngredients: "2 potatoes, 1 small cauliflower, 1/2 cup peas, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp turmeric, 1 tsp cumin powder, 1 tsp coriander powder, 2 tbsp oil, fresh coriander",
        process: "Sauté onions until translucent. Add ginger-garlic paste, tomatoes and spices. Add chopped potatoes and cook for 5 mins. Add cauliflower and peas. Cover and cook until vegetables are tender.",
        time: "35 mins",
        calorie: 300
    },
    {
        title: "Fish Curry",
        type: "Lunch",
        meal: "Non-veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR5bv5CUtCfSyCjiwS29HyMoq0FfaCTGxX1A&s",
        keyIngredient: "Fish",
        subIngredient_1: "Coconut",
        subIngredient_2: "Tamarind",
        otherIngredients: "500g fish pieces, 1 cup coconut milk, 1 tbsp tamarind paste, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp turmeric, 1 tsp red chili powder, curry leaves, 2 tbsp oil",
        process: "Marinate fish with turmeric and salt. Sauté onions, add ginger-garlic paste, tomatoes and spices. Add coconut milk and tamarind. Simmer and gently add fish pieces. Cook for 8-10 mins.",
        time: "40 mins",
        calorie: 380
    },
    {
        title: "Rajma Chawal",
        type: "Lunch",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Qq7E4VxWbfZCjN5t4q42FbMB9LY6fL91mQ&s",
        keyIngredient: "Kidney Beans",
        subIngredient_1: "Rice",
        subIngredient_2: "Onion",
        otherIngredients: "2 cups kidney beans, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp garam masala, 1 tsp coriander powder, 1 tsp cumin powder, 2 tbsp oil, fresh coriander, steamed rice",
        process: "Soak beans overnight and pressure cook. Sauté onions, add ginger-garlic paste, tomatoes and spices. Add cooked beans and simmer for 15 mins. Serve with steamed rice.",
        time: "50 mins",
        calorie: 420
    },
    {
        title: "Kashmiri Dum Aloo",
        type: "Lunch",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe5_BN1-XF74yL_fqb7dri_ydRdgO03ajoTQ&s",
        keyIngredient: "Baby Potatoes",
        subIngredient_1: "Yogurt",
        subIngredient_2: "Fennel Powder",
        otherIngredients: "15 baby potatoes, 1 cup yogurt, 1 tbsp fennel powder, 1 tsp ginger powder, 1/2 tsp asafoetida, 2 tbsp ghee",
        process: "Boil and prick potatoes. Whisk yogurt with spices. Heat ghee, add potatoes and yogurt mixture. Cook covered on low heat for 20 mins. Garnish with coriander.",
        time: "45 mins",
        calorie: 320
    },
    {
        title: "Methi Thepla",
        type: "Lunch",
        meal: "Veg",
        image: "https://i0.wp.com/binjalsvegkitchen.com/wp-content/uploads/2015/01/Methi-Thepla-H1.jpg?fit=600%2C900&ssl=1",
        keyIngredient: "Fenugreek",
        subIngredient_1: "Wheat Flour",
        subIngredient_2: "Yogurt",
        otherIngredients: "2 cups wheat flour, 1 cup chopped fenugreek leaves, 1/2 cup yogurt, 1 tbsp ginger-chili paste, 1 tsp turmeric, 1 tsp cumin powder, 2 tbsp oil, salt to taste",
        process: "Mix all ingredients to make soft dough. Divide into balls and roll into thin rotis. Cook on tawa with oil until golden spots appear. Serve with yogurt or pickle.",
        time: "40 mins",
        calorie: 320
    },
    {
        title: "Malai Kofta",
        type: "Lunch",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsT8TUD-NzEQeESGXCTvbEFMbcMp-heDW-Kw&s",
        keyIngredient: "Paneer",
        subIngredient_1: "Potato",
        subIngredient_2: "Cream",
        otherIngredients: "200g paneer, 1 potato, 1/4 cup cornflour, 1/2 cup cream, 2 tomatoes, 1 onion, 1 tbsp ginger-garlic paste, 1 tsp garam masala, 1 tsp sugar, 2 tbsp oil",
        process: "Mix grated paneer, mashed potato and cornflour to make kofta balls. Deep fry. Make gravy by sautéing onions, ginger-garlic, tomatoes and spices. Add cream. Add koftas just before serving.",
        time: "50 mins",
        calorie: 480
    },
    {
        title: "Dosa with Sambar",
        type: "Lunch",
        meal: "Veg",
        image: "https://media.istockphoto.com/id/1205482290/photo/masala-dosa-on-banana-leaf-with-both-sambar-and-coconut-chutney-south-indian-vegetarian-snack.jpg?s=612x612&w=0&k=20&c=FcujJMpizSvYEj5-2jspq5woZ4F5HloXuOX33CD1MeI=",
        keyIngredient: "Rice",
        subIngredient_1: "Lentils",
        subIngredient_2: "Vegetables",
        otherIngredients: "2 cups rice, 1 cup urad dal, 1/2 tsp fenugreek seeds, salt to taste, oil for cooking. For sambar: 1 cup toor dal, mixed vegetables, 1 tbsp sambar powder, tamarind, curry leaves",
        process: "Soak rice and dal separately for 6 hrs. Grind to smooth batter and ferment overnight. Make thin crepes on hot tawa. For sambar, cook dal and vegetables with sambar powder and tamarind.",
        time: "60 mins (plus soaking)",
        calorie: 380
    },
    {
        title: "Kadhai Paneer",
        type: "Lunch",
        meal: "Veg",
        image: "https://cdn.zeptonow.com/production///tr:w-600,ar-100-100,pr-true,f-auto,q-80/web/recipes/kadai-paneer.png",
        keyIngredient: "Paneer",
        subIngredient_1: "Capsicum",
        subIngredient_2: "Onion",
        otherIngredients: "250g paneer, 1 capsicum, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tbsp kadhai masala, 1 tsp coriander powder, 1/2 cup cream, 2 tbsp oil, fresh coriander",
        process: "Sauté onions, capsicum and paneer separately. In same pan, add ginger-garlic paste, tomatoes and spices. Cook until oil separates. Add vegetables, paneer and cream. Simmer for 5 mins.",
        time: "35 mins",
        calorie: 420
    },
    {
        title: "Vegetable Pulao",
        type: "Lunch",
        meal: "Veg",
        image: "https://rakskitchen.net/wp-content/uploads/2013/11/10719907466_eae85442ea_z.jpg",
        keyIngredient: "Rice",
        subIngredient_1: "Mixed Vegetables",
        subIngredient_2: "Ghee",
        otherIngredients: "2 cups basmati rice, 1 cup mixed vegetables (carrots, beans, peas), 1 onion, whole spices (bay leaf, cardamom, cinnamon), 1 tsp cumin, 2 tbsp ghee, fresh mint",
        process: "Sauté whole spices in ghee. Add onions and vegetables. Add soaked rice and water (1:2 ratio). Cook covered until rice is done. Fluff with fork and garnish with mint.",
        time: "30 mins",
        calorie: 350
    },
    {
        title: "Chicken Chettinad",
        type: "Lunch",
        meal: "Non-veg",
        image: "https://greatcurryrecipes.net/wp-content/uploads/2014/02/chet11-735x980.jpg",
        keyIngredient: "Chicken",
        subIngredient_1: "Coconut",
        subIngredient_2: "Pepper",
        otherIngredients: "500g chicken, 1/2 cup grated coconut, 1 tbsp peppercorns, 1 tbsp fennel seeds, 2 dried red chilies, 1 onion, 2 tomatoes, curry leaves, 2 tbsp oil",
        process: "Dry roast coconut and spices to make masala powder. Sauté onions, add chicken and brown. Add tomatoes and masala powder. Cook until chicken is tender. Finish with curry leaves.",
        time: "45 mins",
        calorie: 460
    },
    {
        title: "Baingan Bharta",
        type: "Lunch",
        meal: "Veg",
        image: "https://www.potsandpans.in/cdn/shop/articles/Baingan_Bharta.jpg?v=1681890534",
        keyIngredient: "Eggplant",
        subIngredient_1: "Tomato",
        subIngredient_2: "Onion",
        otherIngredients: "1 large eggplant, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp cumin, 1 tsp coriander powder, 1/2 tsp garam masala, 2 tbsp oil, fresh coriander",
        process: "Roast eggplant until charred and soft. Peel and mash. Sauté onions, add ginger-garlic paste, tomatoes and spices. Add mashed eggplant and cook for 10 mins. Garnish with coriander.",
        time: "40 mins",
        calorie: 280
    },
    {
        title: "Mutton Rogan Josh",
        type: "Lunch",
        meal: "Non-veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW0EdS7bf44iB_uy4vAos9P9DdY-NdhZeUnw&s",
        keyIngredient: "Mutton",
        subIngredient_1: "Yogurt",
        subIngredient_2: "Kashmiri Chili",
        otherIngredients: "500g mutton, 1 cup yogurt, 2 onions, 1 tbsp ginger-garlic paste, 1 tbsp kashmiri chili powder, 1 tsp fennel powder, 1 tsp garam masala, 2 tbsp ghee, fresh coriander",
        process: "Marinate mutton with yogurt and spices for 2 hrs. Sauté onions until brown. Add ginger-garlic paste and mutton. Cook on low heat until tender (about 1 hr). Finish with garam masala.",
        time: "90 mins",
        calorie: 520
    },
    {
        title: "Masala Khichdi",
        type: "Lunch",
        meal: "Veg",
        image: "https://www.chefajaychopra.com/assets/img/recipe/1-1666340067MasalaKhichdi1webp.webp",
        keyIngredient: "Rice",
        subIngredient_1: "Lentils",
        subIngredient_2: "Ghee",
        otherIngredients: "1 cup rice, 1/2 cup moong dal, 1/2 tsp turmeric, 1 tsp cumin seeds, 1 inch ginger, 2 tbsp ghee, mixed vegetables (optional), salt to taste",
        process: "Wash rice and dal together. In pressure cooker, temper cumin in ghee. Add ginger, rice-dal mixture, turmeric and water (1:3 ratio). Pressure cook for 3 whistles. Serve with yogurt.",
        time: "30 mins",
        calorie: 340
    },
    {
        title: "Punjabi Chole",
        type: "Lunch",
        meal: "Veg",
        image: "https://vegecravings.com/wp-content/uploads/2017/01/chole-recipe-step-by-step-instructions-13.jpg",
        keyIngredient: "Chickpeas",
        subIngredient_1: "Tea Bags",
        subIngredient_2: "Onion",
        otherIngredients: "2 cups chickpeas, 2 tea bags (for color), 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tbsp chole masala, 1 tsp amchur, 2 tbsp oil, fresh coriander, bhatura (optional)",
        process: "Soak chickpeas overnight with tea bags. Pressure cook until soft. Sauté onions, add ginger-garlic paste, tomatoes and spices. Add cooked chickpeas and simmer for 15 mins. Garnish with coriander.",
        time: "50 mins",
        calorie: 380
    },
    {
        title: "Hyderabadi Bagara Rice",
        type: "Lunch",
        meal: "Veg",
        image: "https://i.ytimg.com/vi/mnLV30v7uOc/maxresdefault.jpg",
        keyIngredient: "Rice",
        subIngredient_1: "Tamarind",
        subIngredient_2: "Peanuts",
        otherIngredients: "2 cups basmati rice, 1 tbsp tamarind paste, 1/4 cup peanuts, 1 onion, whole spices (cinnamon, cloves, cardamom), 1 tbsp ginger-garlic paste, 2 tbsp ghee, mint leaves",
        process: "Cook rice until 70% done. In another pan, temper whole spices in ghee. Add onions, peanuts and ginger-garlic paste. Add tamarind and cooked rice. Cook covered on low heat for 15 mins.",
        time: "45 mins",
        calorie: 420
    },
    {
        title: "Masala Dosa",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/masala-dosa-recipe.jpg",
        keyIngredient: "Rice",
        subIngredient_1: "Urad Dal",
        subIngredient_2: "Potato",
        otherIngredients: "2 cups rice, 1 cup urad dal, 1/2 tsp fenugreek seeds, salt to taste, oil for cooking, 4 potatoes (for masala), 1 onion, 2 green chilies, 1/2 tsp turmeric, 1 tsp mustard seeds, curry leaves",
        process: "Soak rice and dal separately for 6 hrs. Grind to smooth batter and ferment overnight. For masala, boil and mash potatoes. Temper mustard seeds, add onions, chilies, curry leaves and spices. Mix with potatoes. Spread batter on hot tawa to make thin dosa, add potato masala and fold.",
        time: "30 mins (plus soaking)",
        calorie: 280
    },
    {
        title: "Poha",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/poha.jpg",
        keyIngredient: "Flattened Rice",
        subIngredient_1: "Peanuts",
        subIngredient_2: "Potato",
        otherIngredients: "2 cups thick poha, 1 onion, 1 potato, 2 tbsp peanuts, 1/2 tsp turmeric, 1 tsp mustard seeds, 1 tsp sugar, 2 tbsp oil, curry leaves, fresh coriander, lemon wedges",
        process: "Rinse poha and drain. Heat oil, temper mustard seeds, add peanuts, curry leaves. Add chopped onions and potatoes, cook until soft. Add turmeric, salt, sugar. Mix in poha gently. Garnish with coriander and lemon.",
        time: "20 mins",
        calorie: 250
    },
    {
        title: "Upma",
        type: "Breakfast",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa9An3jEhdO77Wd7jrkfZg3SEGR_kR9Da46A&s",
        keyIngredient: "Semolina",
        subIngredient_1: "Vegetables",
        subIngredient_2: "Curry Leaves",
        otherIngredients: "1 cup semolina (rava), 1 onion, 1 carrot, 1/2 cup peas, 1 green chili, 1 tsp mustard seeds, 1 tsp urad dal, 2 tbsp oil, curry leaves, lemon wedges",
        process: "Dry roast semolina until fragrant. Heat oil, temper mustard seeds and urad dal. Add onions, chilies, curry leaves and vegetables. Add 2 cups water and salt. When boiling, add roasted semolina slowly while stirring. Cover and cook for 5 mins. Serve with lemon.",
        time: "25 mins",
        calorie: 300
    },
    {
        title: "Aloo Paratha",
        type: "Breakfast",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-eR7eKil_fbqx04GkWqzS-0b8b6hKhx31Kw&s",
        keyIngredient: "Wheat Flour",
        subIngredient_1: "Potato",
        subIngredient_2: "Spices",
        otherIngredients: "2 cups wheat flour, 3 boiled potatoes, 1 tsp cumin powder, 1/2 tsp garam masala, 1 green chili, 2 tbsp oil, salt to taste, butter for serving",
        process: "Mash potatoes and mix with spices. Make dough from flour and water. Roll small roti, place potato mixture, seal and roll again. Cook on tawa with oil until golden spots appear. Serve with butter and pickle.",
        time: "40 mins",
        calorie: 350
    },
    {
        title: "Idli with Sambar",
        type: "Breakfast",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0MYvNjRJxFAS0YUZN6Sk3Ekc0fmLziodMig&s",
        keyIngredient: "Rice",
        subIngredient_1: "Urad Dal",
        subIngredient_2: "Coconut Chutney",
        otherIngredients: "2 cups idli rice, 1 cup urad dal, 1/2 tsp fenugreek seeds, salt to taste. For sambar: 1 cup toor dal, sambar powder, tamarind, vegetables",
        process: "Soak rice and dal separately for 6 hrs. Grind to smooth batter and ferment overnight. Pour into idli molds and steam for 10 mins. Serve with sambar and coconut chutney.",
        time: "30 mins (plus soaking)",
        calorie: 200
    },
    {
        title: "Besan Chilla",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/02/besan-chilla-3.jpg",
        keyIngredient: "Gram Flour",
        subIngredient_1: "Onion",
        subIngredient_2: "Spices",
        otherIngredients: "1 cup besan (gram flour), 1 onion, 1 tomato, 1 green chili, 1/2 tsp turmeric, 1/2 tsp cumin powder, 2 tbsp oil, fresh coriander",
        process: "Mix besan with water to make thin batter. Add chopped onions, tomatoes, chilies and spices. Heat tawa, pour ladleful of batter like pancake. Cook both sides with oil until golden. Serve with chutney.",
        time: "20 mins",
        calorie: 180
    },
    {
        title: "Methi Thepla",
        type: "Breakfast",
        meal: "Veg",
        image: "https://i0.wp.com/binjalsvegkitchen.com/wp-content/uploads/2015/01/Methi-Thepla-H1.jpg?fit=600%2C900&ssl=1",
        keyIngredient: "Fenugreek Leaves",
        subIngredient_1: "Wheat Flour",
        subIngredient_2: "Yogurt",
        otherIngredients: "2 cups wheat flour, 1 cup chopped fenugreek leaves, 1/2 cup yogurt, 1 tbsp ginger-chili paste, 1 tsp turmeric, 1 tsp cumin powder, 2 tbsp oil",
        process: "Mix all ingredients to make soft dough. Divide into balls and roll into thin rotis. Cook on tawa with oil until golden spots appear. Serve with yogurt or pickle.",
        time: "30 mins",
        calorie: 220
    },
    {
        title: "Rava Uttapam",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.chefkunalkapur.com/wp-content/uploads/2021/03/Rava-Uttapam.jpg?v=1619150769",
        keyIngredient: "Semolina",
        subIngredient_1: "Curd",
        subIngredient_2: "Vegetables",
        otherIngredients: "1 cup semolina, 1/2 cup curd, 1 onion, 1 tomato, 1 green chili, 1/2 tsp baking soda, oil for cooking",
        process: "Mix semolina with curd and water to make thick batter. Add baking soda. Pour on hot tawa, top with chopped vegetables. Cook both sides with oil until crisp.",
        time: "25 mins",
        calorie: 240
    },
    {
        title: "Sabudana Khichdi",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/sabudana-khichdi-recipe.jpg",
        keyIngredient: "Tapioca Pearls",
        subIngredient_1: "Peanuts",
        subIngredient_2: "Potato",
        otherIngredients: "1 cup sabudana (soaked), 1 potato, 2 tbsp peanuts, 1 green chili, 1 tsp cumin, 1 tsp sugar, 2 tbsp ghee, fresh coriander",
        process: "Soak sabudana for 4 hrs. Heat ghee, temper cumin, roast peanuts. Add diced potatoes and chilies. Add sabudana, salt and sugar. Cook on low heat until translucent. Garnish with coriander.",
        time: "30 mins",
        calorie: 320
    },
    {
        title: "Missal Pav",
        type: "Breakfast",
        meal: "Veg",
        image: "https://www.ohmyveg.co.uk/wp-content/uploads/2023/12/Misal-Pav-2-2-e1722869218662-540x720.jpg",
        keyIngredient: "Sprouts",
        subIngredient_1: "Pav Bread",
        subIngredient_2: "Spicy Gravy",
        otherIngredients: "1 cup mixed sprouts, 1 onion, 2 tomatoes, 1 tbsp goda masala, 1 tsp tamarind, 1/2 cup farsan, pav bread, fresh coriander",
        process: "Cook sprouts until soft. Make gravy with onions, tomatoes and spices. Add sprouts to gravy. Serve topped with farsan, onions and pav bread on side.",
        time: "40 mins",
        calorie: 380
    },
    {
        title: "Samosa",
        type: "Snacks",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/samosa-recipe.jpg",
        keyIngredient: "Maida",
        subIngredient_1: "Potato",
        subIngredient_2: "Peas",
        otherIngredients: "2 cups maida, 4 potatoes, 1/2 cup peas, 1 tsp cumin seeds, 1 tsp coriander powder, 1/2 tsp garam masala, oil for deep frying",
        process: "Make dough with maida and oil. For filling, boil and mash potatoes. Sauté cumin, add peas and spices. Mix with potatoes. Fill dough cones with mixture and seal. Deep fry until golden.",
        time: "50 mins",
        calorie: 300
    },
    {
        title: "Paneer Tikka",
        type: "Snacks",
        meal: "Veg",
        image: "https://carveyourcraving.com/wp-content/uploads/2021/10/paneer-tikka-skewers-500x500.jpg",
        keyIngredient: "Paneer",
        subIngredient_1: "Bell Peppers",
        subIngredient_2: "Yogurt",
        otherIngredients: "200g paneer, 1 capsicum, 1 onion, 1/2 cup yogurt, 1 tbsp ginger-garlic paste, 1 tsp garam masala, 1 tsp chaat masala, 1 tbsp oil",
        process: "Cut paneer and vegetables into cubes. Marinate with yogurt and spices for 1 hr. Skewer alternately. Grill or bake until charred. Sprinkle chaat masala and serve with mint chutney.",
        time: "40 mins",
        calorie: 280
    },
    {
        title: "Bhel Puri",
        type: "Snacks",
        meal: "Veg",
        image: "https://shwetainthekitchen.com/wp-content/uploads/2022/01/bhel-puri-500x500.jpg",
        keyIngredient: "Puffed Rice",
        subIngredient_1: "Sev",
        subIngredient_2: "Tamarind Chutney",
        otherIngredients: "2 cups puffed rice, 1/2 cup sev, 1 onion, 1 tomato, 1 potato, 2 tbsp tamarind chutney, 2 tbsp green chutney, 1 tsp chaat masala, fresh coriander",
        process: "Mix puffed rice with chopped vegetables. Add both chutneys and mix well. Top with sev, chaat masala and coriander. Serve immediately.",
        time: "15 mins",
        calorie: 200
    },
    {
        title: "Dhokla",
        type: "Snacks",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMQ_ywTsl1l_oEJHiP17VGZoipj8UrGbVs-g&s",
        keyIngredient: "Gram Flour",
        subIngredient_1: "Eno Fruit Salt",
        subIngredient_2: "Mustard Seeds",
        otherIngredients: "1 cup besan, 1 tsp eno fruit salt, 1 tsp mustard seeds, 2 green chilies, 1 tbsp sugar, 1 tbsp oil, fresh coriander",
        process: "Mix besan with water, sugar and salt to make batter. Add eno just before steaming. Pour into greased plate and steam for 15 mins. Temper mustard seeds and chilies in oil, pour over dhokla. Garnish with coriander.",
        time: "30 mins",
        calorie: 180
    },
    {
        title: "Aloo Tikki",
        type: "Snacks",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOQyafz0oXjUQD4VUh1TNb-4s828GZALVcdA&s",
        keyIngredient: "Potato",
        subIngredient_1: "Bread Crumbs",
        subIngredient_2: "Spices",
        otherIngredients: "4 potatoes, 2 tbsp bread crumbs, 1 tsp cumin powder, 1 tsp chaat masala, 1 green chili, oil for shallow frying",
        process: "Boil and mash potatoes. Add bread crumbs, spices and make small patties. Shallow fry until golden brown on both sides. Serve with chutneys.",
        time: "35 mins",
        calorie: 250
    },
    {
        title: "Vada Pav",
        type: "Snacks",
        meal: "Veg",
        image: "https://ministryofcurry.com/wp-content/uploads/2024/06/vada-pav-3.jpg",
        keyIngredient: "Potato",
        subIngredient_1: "Pav Bread",
        subIngredient_2: "Garlic Chutney",
        otherIngredients: "4 potatoes, 1 cup besan, 1 tsp mustard seeds, 2 green chilies, 8 pav buns, garlic chutney, oil for frying",
        process: "Make potato mixture with tempered spices. Dip in besan batter and deep fry. Spread garlic chutney on pav, place vada and serve with fried green chilies.",
        time: "45 mins",
        calorie: 320
    },
    {
        title: "Kachori",
        type: "Snacks",
        meal: "Veg",
        image: "https://www.chefkunalkapur.com/wp-content/uploads/2023/11/DSC08208-1300x731.jpg?v=1699513010",
        keyIngredient: "Maida",
        subIngredient_1: "Moong Dal",
        subIngredient_2: "Spices",
        otherIngredients: "2 cups maida, 1/2 cup moong dal, 1 tsp fennel seeds, 1 tsp coriander powder, 1/2 tsp red chili powder, oil for deep frying",
        process: "Soak and grind moong dal with spices for filling. Make dough with maida. Stuff small dough balls with filling, flatten and deep fry until golden and crisp.",
        time: "60 mins",
        calorie: 350
    },
    {
        title: "Pani Puri",
        type: "Snacks",
        meal: "Veg",
        image: "https://static.toiimg.com/thumb/61048461.cms?imgsize=1981854&width=800&height=800",
        keyIngredient: "Puri",
        subIngredient_1: "Tamarind Water",
        subIngredient_2: "Mint Water",
        otherIngredients: "20 puris, 1 cup boiled potatoes, 1/2 cup cooked chickpeas, 1 cup tamarind chutney, 2 cups mint-coriander water, 1 tsp chaat masala",
        process: "Make small hole in puri. Stuff with potato and chickpeas. Dip in mint water or tamarind chutney as preferred. Eat immediately in one bite.",
        time: "30 mins",
        calorie: 150
    },
    {
        title: "Ragda Pattice",
        type: "Snacks",
        meal: "Veg",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/ragda-patties-recipe-500x500.jpg",
        keyIngredient: "White Peas",
        subIngredient_1: "Potato",
        subIngredient_2: "Chutneys",
        otherIngredients: "1 cup white peas, 4 potatoes, 1 tsp ginger paste, 1 tsp garam masala, tamarind chutney, green chutney, sev, onions",
        process: "Soak and cook white peas with spices to make ragda. Make potato patties. Place patties on plate, pour ragda over them. Top with chutneys, onions and sev.",
        time: "50 mins",
        calorie: 380
    },
    {
        title: "Corn Chaat",
        type: "Snacks",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEU7qmHRtU09SKdASM_o-A1rKH_dfrJ4RJwQ&s",
        keyIngredient: "Sweet Corn",
        subIngredient_1: "Lemon",
        subIngredient_2: "Spices",
        otherIngredients: "2 cups boiled sweet corn, 1 onion, 1 tomato, 1 lemon, 1 tsp chaat masala, 1/2 tsp red chili powder, fresh coriander",
        process: "Mix boiled corn with chopped onions and tomatoes. Add lemon juice, chaat masala and chili powder. Garnish with coriander. Serve immediately.",
        time: "15 mins",
        calorie: 200
    },
    {
        title: "Dal Makhani",
        type: "Dinner",
        meal: "Veg",
        image: "https://www.sharmispassions.com/wp-content/uploads/2012/05/dal-makhani7.jpg",
        keyIngredient: "Black Lentils",
        subIngredient_1: "Kidney Beans",
        subIngredient_2: "Butter",
        otherIngredients: "1 cup whole black lentils, 1/4 cup kidney beans, 2 tbsp butter, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1/2 cup cream, 1 tsp garam masala",
        process: "Soak lentils and beans overnight. Pressure cook until soft. Sauté onions, ginger-garlic and tomatoes. Add cooked dal, simmer for 30 mins. Finish with butter and cream.",
        time: "60 mins",
        calorie: 420
    },
    {
        title: "Malabar Fish Curry",
        type: "Dinner",
        meal: "Non-veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTqTG_kkF7zKf6HI6N6-GP7rI3BHO1Lp72Ig&s",
        keyIngredient: "Fish",
        subIngredient_1: "Coconut",
        subIngredient_2: "Kokum",
        otherIngredients: "500g fish pieces, 1 cup coconut milk, 2 kokum petals, 1 tbsp coriander seeds, 4 dried red chilies, 1/2 tsp fenugreek seeds, curry leaves",
        process: "Grind coconut with spices to make paste. Cook paste with kokum and water. Add fish pieces and simmer for 10 mins. Finish with coconut milk and curry leaves.",
        time: "45 mins",
        calorie: 380
    },
    {
        title: "Baingan Ka Bharta",
        type: "Dinner",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToZymFb9d6t8RUEVxKCBqRsVV8GUfyxbGHhQ&s",
        keyIngredient: "Eggplant",
        subIngredient_1: "Tomato",
        subIngredient_2: "Onion",
        otherIngredients: "1 large eggplant, 2 tomatoes, 1 onion, 2 green chilies, 1 tbsp mustard oil, 1 tsp cumin seeds, fresh coriander",
        process: "Roast eggplant until charred. Peel and mash. Heat mustard oil, temper cumin. Add onions, chilies and tomatoes. Cook until soft. Add mashed eggplant and cook for 10 mins. Garnish with coriander.",
        time: "40 mins",
        calorie: 250
    },
    {
        title: "Kadhi Pakora",
        type: "Dinner",
        meal: "Veg",
        image: "https://www.flourandspiceblog.com/wp-content/uploads/2023/03/IMG_2162.jpg",
        keyIngredient: "Yogurt",
        subIngredient_1: "Besan",
        subIngredient_2: "Pakoras",
        otherIngredients: "2 cups yogurt, 1/2 cup besan, 1 tsp fenugreek seeds, 1 tsp mustard seeds, 10-12 besan pakoras, 1 tbsp ghee",
        process: "Whisk yogurt and besan with water. Temper fenugreek and mustard seeds in ghee. Add yogurt mixture and simmer for 20 mins. Add pakoras just before serving.",
        time: "45 mins",
        calorie: 350
    },
    {
        title: "Mushroom Masala",
        type: "Dinner",
        meal: "Veg",
        image: "https://shwetainthekitchen.com/wp-content/uploads/2023/03/mutter-mushroom.jpg",
        keyIngredient: "Mushrooms",
        subIngredient_1: "Onion",
        subIngredient_2: "Tomato",
        otherIngredients: "300g mushrooms, 1 onion, 2 tomatoes, 1 tbsp ginger-garlic paste, 1 tsp garam masala, 1/2 cup cream, 2 tbsp oil",
        process: "Sauté mushrooms separately. In same pan, cook onions, ginger-garlic and tomatoes. Add spices and cream. Add mushrooms and simmer for 5 mins. Garnish with coriander.",
        time: "35 mins",
        calorie: 280
    },
    {
        title: "Kerala Prawn Curry",
        type: "Dinner",
        meal: "Non-veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWkA_l1Pa7GLSF3mieyfmStLu-EzN7exRTgQ&s",
        keyIngredient: "Prawns",
        subIngredient_1: "Coconut",
        subIngredient_2: "Kokum",
        otherIngredients: "500g prawns, 1 cup coconut milk, 2 kokum petals, 1 tbsp coriander powder, 1 tsp turmeric, curry leaves, coconut oil",
        process: "Marinate prawns with turmeric. Grind coconut with spices to make paste. Cook paste with kokum. Add prawns and cook for 5 mins. Add thick coconut milk and remove from heat.",
        time: "40 mins",
        calorie: 320
    },
    {
        title: "Sarson Ka Saag",
        type: "Dinner",
        meal: "Veg",
        image: "https://binjalsvegkitchen.com/wp-content/uploads/2016/11/Sarson-Ka-Saag-H1.jpg",
        keyIngredient: "Mustard Greens",
        subIngredient_1: "Spinach",
        subIngredient_2: "Makki Ki Roti",
        otherIngredients: "2 bunches mustard leaves, 1 bunch spinach, 1 onion, 2 green chilies, 1 tbsp cornmeal, 2 tbsp ghee, 1 tsp cumin seeds",
        process: "Boil greens until soft. Blend coarsely. Temper cumin in ghee, add onions and chilies. Add greens and cornmeal. Cook for 15 mins. Serve with makki ki roti.",
        time: "60 mins",
        calorie: 300
    },
    {
        title: "Chettinad Chicken",
        type: "Dinner",
        meal: "Non-veg",
        image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Chicken-Chettinad-Curry-2-3.jpg",
        keyIngredient: "Chicken",
        subIngredient_1: "Coconut",
        subIngredient_2: "Pepper",
        otherIngredients: "500g chicken, 1/2 cup grated coconut, 1 tbsp peppercorns, 1 tbsp fennel seeds, 2 dried red chilies, curry leaves, coconut oil",
        process: "Dry roast coconut and spices to make masala powder. Sauté chicken in coconut oil. Add masala powder and cook until chicken is tender. Finish with curry leaves.",
        time: "50 mins",
        calorie: 450
    },
    {
        title: "Vegetable Kofta Curry",
        type: "Dinner",
        meal: "Veg",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJefdJKbWIuzMDGiIcTx2HZEoNgjI033Kmeg&s",
        keyIngredient: "Mixed Vegetables",
        subIngredient_1: "Paneer",
        subIngredient_2: "Cashew Paste",
        otherIngredients: "2 cups mixed vegetables (carrots, beans, peas), 100g paneer, 1/4 cup cashew paste, 1 onion, 2 tomatoes, 1 tsp garam masala, 2 tbsp cream",
        process: "Boil and mash vegetables, mix with crumbled paneer to make koftas. Deep fry. Make onion-tomato gravy with cashew paste. Add koftas just before serving.",
        time: "60 mins",
        calorie: 380
    },
    {
        title: "Kashmiri Dum Aloo",
        type: "Dinner",
        meal: "Veg",
        image: "https://binjalsvegkitchen.com/wp-content/uploads/2015/01/Kashmiri-Dum-Aloo-H1.jpg",
        keyIngredient: "Baby Potatoes",
        subIngredient_1: "Yogurt",
        subIngredient_2: "Fennel Powder",
        otherIngredients: "15 baby potatoes, 1 cup yogurt, 1 tbsp fennel powder, 1 tsp ginger powder, 1/2 tsp asafoetida, 2 tbsp ghee",
        process: "Boil and prick potatoes. Whisk yogurt with spices. Heat ghee, add potatoes and yogurt mixture. Cook covered on low heat for 20 mins. Garnish with coriander.",
        time: "45 mins",
        calorie: 320
    },

];


module.exports = { data: sampleRecipes };